const {test}=require('node:test');
const assert=require('node:assert/strict');
const {analyze}=require('../prompthistory/web/analytics.js');
const {model,draw,WIDTH,HEIGHT}=require('../prompthistory/web/share-card.js');
function report(){
  const rows=[0,1].map(i=>({text:'Private prompt sentinel',tool:'Codex',session_id:'private-session',session_title:'Private title sentinel',
    project:'/private/root/repo',project_name:'Private project sentinel',timestamp:`2026-09-21T10:0${i}:00Z`}));
  const result=analyze(rows,rows,{now:Date.parse('2026-09-22T12:00:00Z')});
  result.filters={search:'Private search sentinel'};
  return result;
}
test('share model contains aggregate data only and anonymizes projects by default',()=>{
  const m=model(report());
  assert.doesNotMatch(JSON.stringify(m),/Private|private/);
  assert.equal(m.projects[0].name,'Project 1');
  assert.equal(m.scope,'Filtered history');
  assert.equal(m.command,'pip install prompt-history');
  assert.equal(m.footer,'Generated by');
});
test('explicit name opt-in adds only project names',()=>{
  const m=model(report(),{showNames:true,theme:'dark'});
  assert.equal(m.projects[0].name,'Private project sentinel');
  assert.doesNotMatch(JSON.stringify(m),/\/private\/root|Private prompt|Private title|Private search|private-session/);
  assert.equal(m.theme,'dark');
});
test('zero selections cannot produce a misleading share card',()=>{
  assert.throws(()=>model({totals:{prompts:0}}),/selection with prompts/);
});
test('timeline preserves zero-activity dates and is capped at sixty days',()=>{
  const a=report();a.earliest='2026-01-01';a.latest='2026-09-21';
  const m=model(a);
  assert.equal(m.dates.length,60);
  assert.equal(m.dates[0].prompts,0);assert.equal(m.dates.at(-1).prompts,2);
});
test('card remains honest when prompts have no dates',()=>{
  const a=report();a.earliest=a.latest=null;a.daily=[];
  const m=model(a);assert.equal(m.range,'Undated prompts');assert.deepEqual(m.dates,[]);
});
test('canvas renders required footer, estimates and all eight metrics within image bounds',()=>{
  const calls=[];
  const ctx={font:'',textAlign:'left',measureText:s=>({width:Array.from(s).length*12}),
    fillText:(text,x,y)=>calls.push({text,x,y}),fillRect:()=>{}};
  const canvas={getContext:()=>ctx};
  const a=report();a.projects[0].name='Very long project name '.repeat(100);
  const m=draw(canvas,a,{showNames:true});
  assert.equal(canvas.width,WIDTH);assert.equal(canvas.height,HEIGHT);
  assert.equal(m.metrics.length,8);
  for(const c of calls){assert.ok(c.x>=0 && c.x<=WIDTH);assert.ok(c.y>=0 && c.y<HEIGHT);}
  assert.ok(calls.some(c=>c.text==='pip install prompt-history'));
  assert.ok(calls.some(c=>c.text==='Generated by'));
  assert.ok(calls.some(c=>c.text.includes('Time is estimated')));
  assert.ok(calls.some(c=>c.text.endsWith('…')));
});
test('canvas unavailability produces an actionable error',()=>{
  assert.throws(()=>draw({getContext:()=>null},report()),/unavailable/);
});
