/* A local image renderer. Only the explicit aggregate model reaches the canvas. */
(function(root){
  "use strict";
  const WIDTH=1200, HEIGHT=1000;
  const number=n=>Number(n||0).toLocaleString("en",{notation:n>=1e6 ? "compact" : "standard",maximumFractionDigits:1});
  function duration(seconds){
    if(!seconds) return "0m";
    if(seconds<60) return "<1m";
    const m=Math.round(seconds/60);
    return m<60 ? `${m}m` : `${Math.floor(m/60)}h ${m%60}m`;
  }
  function model(report,options={}){
    if(!report?.totals?.prompts) throw new Error("Choose a selection with prompts before creating an image.");
    const t=report.totals;
    const projects=[...report.projects].sort((a,b)=>b.words-a.words).slice(0,3);
    const dates=[];
    if(report.latest && report.earliest){
      const end=new Date(report.latest+"T12:00:00"),start=new Date(end);
      start.setDate(start.getDate()-59);
      const first=new Date(report.earliest+"T12:00:00");
      const counts=new Map(report.daily.map(d=>[d.date,d.prompts]));
      for(let day=new Date(Math.max(start,first));day<=end;day.setDate(day.getDate()+1)){
        const key=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,"0")}-${String(day.getDate()).padStart(2,"0")}`;
        dates.push({date:key,prompts:counts.get(key)||0});
      }
    }
    // Do not copy paths, search terms, session titles, or original prompts.
    return {title:"Your prompting activity",range:report.earliest ? `${report.earliest} to ${report.latest}` : "Undated prompts",
      scope:Object.values(report.filters||{}).some(v=>v && v!=="all") ? "Filtered history" : "Local history",
      theme:options.theme==="dark" ? "dark" : "light",showNames:!!options.showNames,
      metrics:[["Prompts",number(t.prompts)],["Words",number(t.words)],["Approx. sentences",number(t.sentences)],["Characters",number(t.characters)],
        ["Activity estimate",duration(t.activitySeconds)],["Typing estimate",duration(t.typingSeconds)],["Active days",number(t.activeDays)],["Projects",number(t.projects)]],
      projects:projects.map((p,i)=>({name:options.showNames ? String(p.name||"Unknown project") : `Project ${i+1}`,words:p.words})),
      dates,settings:`Time is estimated · ${number(report.methodology.wpm)} WPM · ${number(report.methodology.idleMinutes)}-minute idle cutoff`,
      footer:"Generated by",command:"pip install prompt-history"};
  }
  function fit(ctx,text,x,y,maxWidth,size,color,weight=400){
    ctx.fillStyle=color;
    ctx.font=`${weight} ${size}px system-ui, -apple-system, "Segoe UI", sans-serif`;
    const clean=String(text).replace(/\s+/g," ");
    let output=clean;
    if(ctx.measureText(clean).width>maxWidth){
      const chars=Array.from(clean);
      let low=0,high=chars.length;
      while(low<high){
        const mid=Math.ceil((low+high)/2);
        if(ctx.measureText(chars.slice(0,mid).join("")+"…").width<=maxWidth) low=mid;
        else high=mid-1;
      }
      output=chars.slice(0,low).join("")+"…";
    }
    ctx.fillText(output,x,y);
  }
  function draw(canvas,report,options={}){
    const m=model(report,options);
    canvas.width=WIDTH;canvas.height=HEIGHT;
    const c=canvas.getContext("2d");
    if(!c) throw new Error("Image rendering is unavailable in this browser.");
    const dark=m.theme==="dark";
    const p=dark ? {bg:"#141417",ink:"#e7e7ea",muted:"#a1a1aa",line:"#34343b",accent:"#6fcbb2"}
      : {bg:"#fcfcfd",ink:"#18181b",muted:"#52525b",line:"#e3e3e7",accent:"#0d6553"};
    c.fillStyle=p.bg;c.fillRect(0,0,WIDTH,HEIGHT);
    c.fillStyle=p.accent;c.fillRect(64,56,42,5);
    fit(c,m.title,64,128,1072,52,p.ink,650);
    fit(c,`${m.range} · ${m.scope}`,64,172,1072,22,p.muted);
    const rule=y=>{c.fillStyle=p.line;c.fillRect(64,y,1072,1);};
    rule(205);
    m.metrics.forEach(([label,value],i)=>{
      const x=64+(i%4)*278,y=248+Math.floor(i/4)*114;
      fit(c,label,x,y,250,20,p.muted);
      fit(c,value,x,y+49,250,40,p.ink,620);
    });
    rule(449);
    fit(c,"Daily prompt activity",64,492,700,24,p.ink,600);
    fit(c,"Latest 60 days in this selection",730,492,406,19,p.muted);
    const max=Math.max(1,...m.dates.map(d=>d.prompts));
    const step=1072/Math.max(1,m.dates.length);
    m.dates.forEach((d,i)=>{
      const h=d.prompts/max*115,w=Math.min(28,step-3);
      c.fillStyle=p.accent;
      if(h) c.fillRect(64+step*i+(step-w)/2,635-h,w,h);
    });
    rule(636);
    if(m.dates.length){
      fit(c,m.dates[0].date,64,665,400,18,p.muted);
      fit(c,m.dates[m.dates.length-1].date,1005,665,135,18,p.muted);
    } else fit(c,"No dated activity recorded",64,566,900,22,p.muted);
    fit(c,"Most writing by project",64,723,700,24,p.ink,600);
    fit(c,m.showNames ? "Project names included" : "Project names hidden",870,723,266,18,p.muted);
    m.projects.forEach((proj,i)=>{
      const y=767+i*40;
      fit(c,String(i+1).padStart(2,"0"),64,y,48,18,p.muted);
      fit(c,proj.name,122,y,750,23,p.ink,500);
      fit(c,number(proj.words)+" words",928,y,210,21,p.ink);
    });
    fit(c,m.settings,64,898,1072,18,p.muted);
    rule(921);
    fit(c,m.footer,64,961,250,18,p.muted);
    c.font='19px ui-monospace, "Cascadia Code", Consolas, monospace';
    c.fillStyle=p.muted;c.textAlign="right";
    c.fillText(m.command,1136,961);c.textAlign="left";
    return m;
  }
  const api={model,draw,WIDTH,HEIGHT};
  if(typeof module==="object" && module.exports) module.exports=api;
  else root.PromptShareCard=api;
})(typeof globalThis!=="undefined" ? globalThis : this);
