"""Core data types shared by every source adapter."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any


# A slash command reaches the transcript as tagged markup rather than as the
# "/name args" the user typed. Rebuild that before anything else strips it.
_COMMAND_NAME = re.compile(r"<command-name>(.*?)</command-name>", re.S)
_COMMAND_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S)

# Markup the CLIs wrap around a turn that the user never typed.
_STRIP_BLOCKS = [
    re.compile(r'<in-app-browser-context\b[^>]*>.*?</in-app-browser-context>', re.S),
    re.compile(r'<(?:recommended_plugins|app-context|skills_instructions|permissions instructions)\b[^>]*>.*?</(?:recommended_plugins|app-context|skills_instructions|permissions instructions)>', re.S),
    re.compile(r'<codex_internal_context\b[^>]*>.*?</codex_internal_context>', re.S),
    re.compile(r'<(?:task-notification|task_notification|teammate-message)\b[^>]*>.*?</(?:task-notification|task_notification|teammate-message)>', re.S),
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S),
    re.compile(r"<environment_context>.*?</environment_context>", re.S),
    re.compile(r"<user_instructions>.*?</user_instructions>", re.S),
    re.compile(r"<environment_details>.*?</environment_details>", re.S),
    re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.S),
    re.compile(r"<command-message>.*?</command-message>", re.S),
    re.compile(r"<ide_[a-z_]+>.*?</ide_[a-z_]+>", re.S),
    # Commands run in the CLI's terminal pane are logged as user turns, but
    # they were typed at a shell, not sent to the model.
    re.compile(r"<bash-input>.*?</bash-input>", re.S),
    re.compile(r"<bash-stdout>.*?</bash-stdout>", re.S),
    re.compile(r"<bash-stderr>.*?</bash-stderr>", re.S),
    re.compile(r"<command-name>.*?</command-name>", re.S),
    re.compile(r"<command-args>.*?</command-args>", re.S),
    re.compile(r"<command-contents>.*?</command-contents>", re.S),
]

# A turn that is *only* one of these is machine-generated, not a prompt.
_NOISE_EXACT = {
    "",
    "(no content)",
    "[Request interrupted by user]",
    "[Request interrupted by user for tool use]",
    "API Error: Request was aborted.",
}

_NOISE_PREFIX = (
    "The following is the Codex agent history",
    ">>> ROOT CONVERSATION START",
    ">>> TRANSCRIPT",
    "Caveat: The messages below were generated by the user while running",
    "[Request interrupted",
    "This session is being continued from a previous conversation",
    "Your task is to create a detailed summary of the conversation",
)


def clean_text(raw: str) -> str:
    """Strip injected markup and whitespace, leaving what the human typed."""
    if not isinstance(raw, str):
        return ""
    text = raw
    if text.startswith("<!-- attach -->"):
        text = text[len("<!-- attach -->"):].lstrip()

    name = _COMMAND_NAME.search(text) if text.lstrip().startswith(("<command-name>", "<command-message>")) else None
    if name:
        args = _COMMAND_ARGS.search(text)
        rebuilt = name.group(1).strip()
        if args and args.group(1).strip():
            rebuilt += " " + args.group(1).strip()
        return rebuilt

    # Preserve literal examples in fenced/inline code, including XML examples.
    tokens = re.compile(r"(?P<code>```[^\n]*\n.*?(?:```|\Z)|~~~[^\n]*\n.*?(?:~~~|\Z)|`[^`\n]+`)|" + "|".join(p.pattern for p in _STRIP_BLOCKS), re.S)
    text = tokens.sub(lambda m: m[0] if m.group("code") is not None else "", text)
    return text.strip()


def is_noise(text: str) -> bool:
    if text in _NOISE_EXACT:
        return True
    return any(text.startswith(p) for p in _NOISE_PREFIX)


def to_iso(value: Any) -> str | None:
    """Accept epoch seconds/ms or an ISO string; return normalised UTC ISO."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        seconds = value / 1000 if value > 1e11 else value
        try:
            return datetime.fromtimestamp(seconds, tz=timezone.utc).isoformat()
        except (OverflowError, OSError, ValueError):
            return None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            return None
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(timezone.utc).isoformat()
    return None


def epoch(iso: str | None) -> float:
    if not iso:
        return 0.0
    try:
        return datetime.fromisoformat(iso).timestamp()
    except ValueError:
        return 0.0


@dataclass
class Prompt:
    text: str
    source: str                      # claude-code | codex | codex-history | codex-catalog
    session_id: str
    timestamp: str | None = None
    project: str | None = None       # absolute cwd the session ran in
    git_branch: str | None = None
    model: str | None = None
    origin_file: str | None = None
    turn: int = 0                    # 1-based position within the session

    id: str = ""
    kind: str = "prompt"             # prompt | slash-command
    words: int = 0
    chars: int = 0
    preview: str = ""
    references: list[dict] = field(default_factory=list)
    recovery_note: str | None = None

    def __post_init__(self) -> None:
        self.chars = len(self.text)
        self.words = len(self.text.split())
        self.kind = "slash-command" if self.text.lstrip().startswith("/") else "prompt"
        first = self.text.strip().splitlines()[0] if self.text.strip() else ""
        self.preview = first[:160]
        if not self.id:
            digest = hashlib.sha1(
                f"{self.source}|{self.session_id}|{self.turn}|{self.text}".encode()
            )
            self.id = digest.hexdigest()[:16]

    @property
    def sort_key(self) -> tuple[float, int]:
        return (epoch(self.timestamp), self.turn)


@dataclass
class Session:
    id: str
    source: str
    title: str | None = None
    project: str | None = None
    git_branch: str | None = None
    model: str | None = None
    origin_file: str | None = None
    started_at: str | None = None
    ended_at: str | None = None
    prompts: list[Prompt] = field(default_factory=list)
    note: str | None = None          # e.g. "titles only, no prompt text stored"
    section: str | None = None
    is_subagent: bool = False

    def finalise(self) -> "Session":
        self.prompts.sort(key=lambda p: p.sort_key)
        for i, prompt in enumerate(self.prompts, start=1):
            prompt.turn = i
        stamps = [p.timestamp for p in self.prompts if p.timestamp]
        if stamps:
            self.started_at = self.started_at or min(stamps)
            self.ended_at = self.ended_at or max(stamps)
        if not self.title and self.prompts:
            self.title = self.prompts[0].preview
        return self

    def to_dict(self) -> dict:
        data = asdict(self)
        data["prompts"] = [asdict(p) for p in self.prompts]
        data["prompt_count"] = len(self.prompts)
        data["project_name"] = project_name(self.project)
        return data


def project_name(path: str | None) -> str:
    if not path:
        return "(no project)"
    cleaned = path.rstrip("/\\")
    return cleaned.rsplit("/", 1)[-1].rsplit("\\", 1)[-1] or cleaned
